# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0257935328a00cc9d0ffb1a963736dc7093ed89a5879781ff15350e876521ae0905d75d09123ad94691d74d7bd0e276cd5a1f79fd41207b2177c7fd43b4af80b

test:
  secret_key_base: fe6937c45fda419ceaf982f9a2c28c76a3603a364c0c31159e08eb7da9f3c2f109a3a6c9f6e0c3231a4249ba1a7c7c0ac92c8a2051715ab8c39870eac9351c8c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
